# Generated by Django 4.0.4 on 2022-12-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demandes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('etablishment_type', models.CharField(choices=[('H', 'Hôtel'), ('R', 'Restaurant'), ('LV', 'Location de voiture')], max_length=200)),
                ('status', models.CharField(choices=[('EC', 'En cours'), ('R', 'Rejetée'), ('AC', 'Accepteé')], default='EC', max_length=200)),
                ('date_added', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
