# Generated by Django 4.0.4 on 2022-11-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
